"""
Generate a Frida JS hook script from elfinfo disasm.json output.

The generated script attaches to a running process, hooks every exported
function (or a filtered subset), and logs return values + this pointer as
JSON lines to the console.

Usage of the generated script:
  frida -p <pid>          -l frida_hooks.js
  frida -n <process_name> -l frida_hooks.js
  frida -f <binary>       -l frida_hooks.js --no-pause
"""
import json
import re
from pathlib import Path


_JS_HEADER = """\
// Generated by elfinfo frida subcommand.
//
// Usage:
//   frida -p <pid>           -l {out_name}
//   frida -n <process_name>  -l {out_name}
//   frida -f <binary>        -l {out_name} --no-pause
//
// Each hook emits one JSON line per call:
//   {{"fn":"<name>","rtype":"<inferred>","ret":<value>[,"this_ptr":"<addr>"]}}

'use strict';

var _LIB  = "{lib}";
var _BASE = Module.findBaseAddress(_LIB);
if (!_BASE) {{
    console.error("[elfinfo] ERROR: " + _LIB + " not found in process");
}} else {{
    console.log("[elfinfo] " + _LIB + " base: " + _BASE);
}}

function _fmt(retval, rtype) {{
    try {{
        if (rtype.indexOf("float")   !== -1 ||
            rtype.indexOf("double")  !== -1) return retval.toString();
        if (rtype.indexOf("bool")    !== -1) return Boolean(retval.toInt32() & 0xff);
        if (rtype.indexOf("pointer") !== -1 ||
            rtype.indexOf("void*")   !== -1) return retval.toString();
        if (rtype.indexOf("int")     !== -1 ||
            rtype.indexOf("short")   !== -1) return retval.toInt32();
        return retval.toString();
    }} catch(e) {{ return retval.toString(); }}
}}

var _hooks = [
"""

_JS_FOOTER = """\
];

var _ok = 0, _fail = 0;
_hooks.forEach(function(h) {
    if (!_BASE) return;
    try {
        Interceptor.attach(_BASE.add(h.rva), {
            onEnter: function(args) {
                this._h    = h;
                this._this = h.method ? args[0].toString() : null;
            },
            onLeave: function(retval) {
                var rec = {rva: this._h.rva, fn: this._h.name, rtype: this._h.rtype, ret: _fmt(retval, this._h.rtype)};
                if (this._this) rec.this_ptr = this._this;
                console.log(JSON.stringify(rec));
            }
        });
        _ok++;
    } catch(e) { _fail++; }
});

console.log("[elfinfo] hooked " + _ok + " / " + _hooks.length
    + " functions  (failed: " + _fail + ")");
"""


def generate(
    disasm_json:  str | Path,
    out_path:     str | Path | None = None,
    filter_pat:   str | None = None,
    include_void: bool = False,
) -> None:
    """
    Read disasm.json and write a Frida hook script.

    Args:
        disasm_json:  Path to the disasm.json produced by elfinfo disasm.
        out_path:     Where to write the .js file.  Defaults to
                      frida_hooks.js alongside disasm_json.
        filter_pat:   Optional regex applied to the demangled function name.
                      Only matching functions are hooked.
        include_void: Include void-return functions (default: False, they
                      produce no useful return value to observe).
    """
    disasm_json = Path(disasm_json)
    if not disasm_json.exists():
        raise FileNotFoundError(disasm_json)

    with open(disasm_json) as f:
        data = json.load(f)

    lib_name  = data.get("file", "unknown.so")
    functions = data.get("functions", [])

    pat = re.compile(filter_pat, re.IGNORECASE) if filter_pat else None

    selected = []
    for fn in functions:
        dem   = fn.get("demangled", "")
        rtype = fn.get("return_type", "unknown")

        if pat and not pat.search(dem):
            continue
        if not include_void and rtype.startswith("void") and "/" not in rtype:
            continue

        selected.append(fn)

    if out_path is None:
        out_path = disasm_json.parent / "frida_hooks.js"
    out_path = Path(out_path)

    entries = []
    for fn in selected:
        addr      = int(fn["addr"], 16)
        name      = fn.get("demangled", fn.get("raw", "unknown")).replace('"', '\\"')
        rtype     = fn.get("return_type", "unknown").replace('"', '\\"')
        is_method = "true" if fn.get("path") else "false"
        entries.append(
            f'    {{rva: 0x{addr:x}, name: "{name}", rtype: "{rtype}", method: {is_method}}}'
        )

    js  = _JS_HEADER.format(lib=lib_name, out_name=out_path.name)
    js += ",\n".join(entries) + "\n"
    js += _JS_FOOTER
    out_path.write_text(js)

    skipped = len(functions) - len(selected)
    print(f"  library  : {lib_name}")
    print(f"  functions: {len(selected)} hooked  ({skipped} skipped)")
    if filter_pat:
        print(f"  filter   : {filter_pat}")
    print(f"  wrote    : {out_path}")
    if len(selected) > 500:
        print(f"\n  warning: {len(selected)} hooks will have significant runtime overhead.")
        print( "  use --filter <pattern> to narrow the scope, e.g. --filter mkvparser")
    print(f"\nUsage:")
    print(f"  frida -n <process_name>  -l {out_path.name}")
    print(f"  frida -p <pid>           -l {out_path.name}")
